apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "trigger-gcp-cloudbuild.fullname" . }}
  labels:
    app: {{ template "trigger-gcp-cloudbuild.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "trigger-gcp-cloudbuild.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: google-secrets
        secret:
          secretName: google-application-credentials
      containers:
      - name: {{ .Chart.Name }}
        image: docker.io/r6by/trigger-gcp-cloudbuild:latest
        volumeMounts:
        - name: google-secrets
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: PROJECT_ID
          value: {{ .Values.projectID }}
