{{- if ne (printf "%s" .Values.projectID) "Must set GCP project ID" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "trigger-gcp-cloudbuild.fullname" . }}-trigger
  labels:
    app: {{ template "trigger-gcp-cloudbuild.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "trigger-gcp-cloudbuild.name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      volumes:
      - name: google-secrets
        secret:
          secretName: google-application-credentials
      containers:
      - name: {{ template "trigger-gcp-cloudbuild.fullname" . }}-trigger
        image: {{ .Values.trigger.image }}
        volumeMounts:
        - name: google-secrets
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: PROJECT_ID
          value: {{ .Values.projectID }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "trigger-gcp-cloudbuild.fullname" . }}-built
  labels:
    app: {{ template "trigger-gcp-cloudbuild.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: {{ template "trigger-gcp-cloudbuild.fullname" . }}-built
        image: {{ printf "gcr.io/%s/built-by-gcp-cloudbuild" .Values.projectID }}
{{- end }}
